### ISSUE TITLE
How to set up the Configuration?

### ISSUE THREAD

**Issue by kklod** [andreasgerstmayr/fava-income-reports#2]
I'm running it on my RaspberriPi 4B . I didn't see the 'example' nor the 'Templates ' folder after pip install…

I can see the sankey chart as below (by the way, it seems too huge for me …)
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/50442661/180444498-5b167ca1-c7a3-4553-a59b-cda0218b2cac.png">

But I cannot see the Monthly PnL chart. Fava reports error as below:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/50442661/180444853-d9f65cf5-5a6b-48ef-864f-d096c50a4ffe.png">

How can I set up?  Should I make new files named 'monthly_pnl.yaml ' ? where should I make it?

Many thanks! 😁

**Comment by andreasgerstmayr** [comment]
hi @kklod 

> I'm running it on my RaspberriPi 4B . I didn't see the 'example' nor the 'Templates ' folder after pip install…

They should be in the site-packages folder of your Python installation.
 
> I can see the sankey chart as below (by the way, it seems too huge for me …) <img alt="image" width="1678" src="https://user-images.githubusercontent.com/50442661/180444498-5b167ca1-c7a3-4553-a59b-cda0218b2cac.png">

Yep, I'm aware the format could be better. Basically it depends on your account hierarchy - the larger, the more space is required. You can click on Left, Justify or Right to change the appearance of the Sankey.

> But I cannot see the Monthly PnL chart. Fava reports error as below: <img alt="image" width="720" src="https://user-images.githubusercontent.com/50442661/180444853-d9f65cf5-5a6b-48ef-864f-d096c50a4ffe.png">
> 
> How can I set up? Should I make new files named 'monthly_pnl.yaml ' ? where should I make it?

Yes, you need to create a new file called `monthly_pnl.yaml` in the same folder as your main `.beancount` file (i.e. the folder from where you start `fava`). You can look at the example file here: https://github.com/andreasgerstmayr/fava-income-reports/blob/main/example/monthly_pnl.yaml

**Comment by kklod** [comment]
Thanks bro！
